# Generated by Django 3.1.3 on 2020-11-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://shahpourpouyan.com/wp-content/uploads/2018/10/orionthemes-placeholder-image-1.png', max_length=500),
        ),
    ]
