# Generated by Django 3.1.3 on 2020-11-23 16:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20201123_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 16, 6, 8, 563891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 16, 6, 8, 563931, tzinfo=utc)),
        ),
    ]
